module.exports = [
  {
    name: "English",
    code: "eng",
    languageObj: {
      welcome: "Welcome",
      Set_Roles: "Set Roles",
      View_Application: "View Application",
      Configurations: "Configurations",
      Earning: "Earning",
      Event_Name: "Event Name",
      Start_Date: "Start Date",
      End_Date: "End Date",
      Leave_Type: "Leave Type",
      Department: "Department",
      Employee: "Employee",
      Request_Duration: "Request Duration",
      Applied_On: "Applied On",
      File: "File",
      Uploaded_Date: "Uploaded Date",
      Citizenship: "Citizenship",
      Eligible: "Eligible",
      Total_Taxable_Amount: "Total Taxable Amount",
      IR8A_D9: "IR8A D9",
      Accommodation: "Accommodation",
      Utilities_and_Housekeeping: "Utilities & Housekeeping",
      Hotel_Accommodation: "Hotel Accommodation",
      Others: "Others",
      Total_Gross_Amount_of_Gains_EEBR: "Total Gross Amount of Gains EEBR",
      Total_Gross_Amount_of_Gains_ESIR: "Total Gross Amount of Gains ESIR",
      Month_Year: "Month Year",
      CSN: "CSN",
      No_Of_Employees: "No Of Employees",
      No_Of_Records: "No Of Records",
      Total_Amount: "Total Amount",
      Date_Created: "Date Created",
      YTD_Gross_Salary: "YTD Gross Salary",
      YTD_Bonus: "YTD Bonus",
      YTD_CPF: "YTD CPF",
      Gross_Salary_Amount: "Gross Salary Amount",
      Bonus_Amount: "Bonus Amount",
      Director_Fees: "Director Fees",
      Total: "Total",
      CPF_Amount: "CPF Amount",
      Title: "Title",
      Company: "Company",
      Company_Name: "Company Name",
      Email: "Email",
      Country: "Country",
      Currency: "Currency",
      Timezone: "Timezone",
      Created_At: "Created At",
      Department_Name: "Department Name",
      Location: "Location",
      Designation: "Designation",
      Grouping_Name: "Grouping Name",
      Location_Head: "Location Head",
      City: "City",
      Added_By: "Added By",
      Location_Name: "Location Name",
      Name: "Name",
      Main_Department: "Main Department",
      Payroll_Type: "Payroll Type",
      Salary: "Salary",
      CPF_Employee: "CPF Employee",
      Net_Salary: "Net Salary",
      Status: "Status",
      HR_Information: "HR Information",
      Attendace_Report: "Attendace Report",
      Date: "Date",
      Clock_In: "Clock In",
      Clock_In_Lattidue: "Clock In Lattidue",
      Clock_In_Longitude: "Clock In Longitude",
      Clock_Out: "Clock Out",
      Clock_Out_Lattidue: "Clock Out Lattidue",
      Clock_Out_Longitude: "Clock Out Longitude",
      Total_Work: "Total Work",
      ID: "ID",
      Employee_ID: "Employee ID",
      Employee_Name: "Employee Name",
      Paid_Amount: "Paid Amount",
      Payment_Month: "Payment Month",
      Payment_Date: "Payment Date",
      Payslip_Type: "Payslip Type",
      Role: "Role",
      Award_Name: "Award Name",
      Gift: "Gift",
      Month_and_Year: "Month & Year",
      From_Employee: "From Employee",
      Complaint_Title: "Complaint Title",
      Complaint_Date: "Complaint Date",
      Period: "Period",
      Rent_Paid: "Rent Paid",
      Address: "Address",
      Annual_Value: "Annual Value",
      Furnished: "Furnished",
      Rent: "Rent",
      Benefit_Year: "Benefit Year",
      Driver_Annual_Wage: "Driver Annual Wage",
      Hotel: "Hotel",
      Check_In: "Check In",
      Check_Out: "Check Out",
      Annual_Cost: "Annual Cost",
      Employee_Paid: "Employee Paid",
      Service: "Service",
      Remarks: "Remarks",
      Annual_Wage: "Annual Wage",
      Benefit: "Benefit",
      Actual_Cost: "Actual Cost",
      Utility: "Utility",
      Remark: "Remark",
      Amount: "Amount",
      Exit_Type: "Exit Type",
      Exit_Date: "Exit Date",
      Exit_Interview: "Exit Interview",
      Contact: "Contact",
      Report_To: "Report To",
      Promotion_Title: "Promotion Title",
      Notice_Date: "Notice Date",
      Resignation_Date: "Resignation Date",
      id: "id",
      name: "name",
      Role_Name: "Role Name",
      Transfer_Date: "Transfer Date",
      Place_of_Visit: "Place of Visit",
      Warning_To: "Warning To",
      Warning_By: "Warning By",
      Warning_Type: "Warning Type",
      Warning_Subject: "Warning Subject",
      Warning_Date: "Warning Date",
      Award: "Award",
      Claim_Type: "Claim Type",
      Company_Type: "Company Type",
      Contract_Type: "Contract Type",
      Code: "Code",
      Symbol: "Symbol",
      Document_Type: "Document Type",
      Employee_Exit: "Employee Exit",
      Expense: "Expense",
      Incom: "Incom",
      Education_Level: "Education Level",
      Language: "Language",
      Skill: "Skill",
      Riligion: "Riligion",
      Travel_Arrangement_Type: "Travel Arrangement Type",
      key: "key",
      value: "value",
      Monday: "Monday",
      Tuesday: "Tuesday",
      Wednesday: "Wednesday",
      Thursday: "Thursday",
      Friday: "Friday",
      Saturday: "Saturday",
      Sunday: "Sunday",
    },
  },
];
